const Erros = {
    CPF_INVALIDO: 'CPF_INVALIDO',
    CNPJ_INVALIDO: 'CNPJ_INVALIDO',
    ID_INVALIDO: 'ID_INVALIDO',
    TIPO_LANCAMENTO_INVALIDO: 'TIPO_LANCAMENTO_INVALIDO',
    CODIGO_ACAO_INVALIDO: 'CODIGO_ACAO_INVALIDO',
    VALOR_EM_CENTAVOS_INVALIDO: 'VALOR_EM_CENTAVOS_INVALIDO',
    VALOR_INVALIDO: 'VALOR_INVALIDO',
    LANCAMENTO_FRACIONARIO_MENOR: 'LANCAMENTO_FRACIONARIO_MENOR',
    LANCAMENTO_AVISTA_QUNATIDADE_INVALIDA: 'LANCAMENTO_AVISTA_QUNATIDADE_INVALIDA',
    DATA_MAIOR_ATUAL: 'DATA_MAIOR_ATUAL',
    USER_NOT_FOUND: 'USER_NOT_FOUND',
    NOME_NAO_INFORMADO: 'NOME_NAO_INFORMADO',
    NOME_INCOMPLETO_SOBRENOME_NECESSARIO: 'NOME_INCOMPLETO_SOBRENOME_NECESSARIO',
    EMAIL_INVALIDO: 'EMAIL_INVALIDO',
    HASH_INVALIDO: 'HASH_INVALIDO',
    SENHA_FRACA: 'SENHA_FRACA',
    USUARIO_JA_CADASTRADO: 'USUARIO_JA_CADASTRADO',
    USUARIO_OU_SENHA_INVALIDO: 'USUARIO_OU_SENHA_INVALIDO',
} as const

export default Erros